"""Prompts for Satisdefying — AI-generated ASMR/satisfying Shorts via Sora 2."""

from packages.prompts.idea_detail import build_ideas_prompt_wrapper


# System prompt shared between ideas and full concepts
_SYSTEM = """You generate concepts for AI-generated oddly satisfying / ASMR YouTube Shorts.

IMPORTANT — AI VIDEO LIMITATIONS:
These videos are generated by an AI model (Sora 2). The AI is GOOD at:
- Smooth fluid dynamics (pouring, dripping, flowing, melting)
- Color transformations (mixing paints, ink in water, color-changing reactions)
- Natural phenomena (lava flows, waves, clouds, crystals forming)
- Slow graceful motion (falling objects, ripples, spreading patterns)
- Large-scale environmental scenes (landscapes, water, sky, nature)

The AI is BAD at:
- Precise tool interactions (cutting with knives often looks fake/stuck)
- Hands and fingers manipulating objects
- Objects cleanly splitting or breaking apart on cue
- Mechanical actions (pressing, cranking, squeezing)
- Small detailed close-up actions that require exact physics

DESIGN CONCEPTS AROUND WHAT AI DOES WELL. Focus on:
- Flowing, pouring, melting, dripping — fluids are Sora's strength
- Color mixing and transformation — paint swirls, ink drops, dye reactions
- Natural satisfying phenomena — crystals growing, ice melting, lava cooling
- Macro nature — dewdrops, frost forming, flowers blooming in slow-mo
- Scale and spectacle — waterfalls of unusual liquids, rivers of color

AVOID concepts that require:
- A knife or tool cleanly cutting through something (Sora can't do this well)
- Hands pressing, squeezing, or manipulating objects
- Objects splitting perfectly in half
- Mechanical devices (hydraulic presses, machines)

Each clip should be visually COMPLETE on its own — the satisfaction comes from watching the flow/transformation, not from a precise physical interaction.

CRITICAL — CLIP COUNT:
- Prefer 1-2 clips, NOT 3. A single 8-second satisfying moment is better than 3 disjointed scenes.
- If using 2 clips: they must show the SAME object/scene from the SAME angle — just a continuation, not a scene change.
- NEVER jump to a completely different view or object between clips. The viewer should feel like it's one continuous video.
- One perfect satisfying loop > three mediocre disconnected scenes."""


def build_satisdefying_ideas_prompt(
    past_titles: list[str] | None = None,
    count: int = 5,
) -> tuple[str, str]:
    """Phase 1: Generate lightweight concept pitches (no Sora prompts)."""
    return build_ideas_prompt_wrapper(_SYSTEM, past_titles, count)


def build_satisdefying_concepts_prompt(
    past_titles: list[str] | None = None,
    count: int = 5,
) -> tuple[str, str]:
    """Return (system, user) prompts for generating satisfying video concepts."""
    past_text = ""
    if past_titles:
        recent = past_titles[-30:]
        past_text = f"\nAVOID THESE CONCEPTS (already made):\n" + "\n".join(f"- {t}" for t in recent)

    system = _SYSTEM + "\n\nEach concept is a 2-3 clip satisfying visual experience."

    user = f"""Generate {count} satisfying/ASMR concepts. Focus on FLOWING, POURING, MIXING, and NATURAL phenomena — NOT cutting or tool-based actions.

EXAMPLE:
{{
  "title": "Liquid Gold Poured Over Black Ice",
  "sora_prompts": [
    "Extreme slow motion of thick molten gold liquid being poured from above onto a perfectly smooth block of black ice, the gold flowing and spreading across the surface, steam rising where hot meets cold, warm golden light reflecting off the liquid, macro photography, 100mm lens, shallow depth of field, dark background, satisfying pouring ASMR sound",
    "Same black ice block with the gold now flowing over the edges in thick rivulets, the ice surface cracking with golden veins spreading through it like lightning, steam swirling upward, macro 100mm lens, same warm golden lighting against dark background, crackling and hissing sounds",
    "Wide macro shot of the gold solidifying on the ice surface creating an intricate frozen pattern, golden fractals and branching crystals visible, the remaining steam dissipating, same warm golden lighting, dark background, soft crystallization sounds"
  ],
  "caption": "When two extremes meet",
  "description": "Liquid gold vs black ice — pure satisfaction. #oddlysatisfying #asmr #Shorts #satisfying",
  "tags": ["oddly satisfying", "ASMR", "liquid gold", "satisfying", "Shorts"],
  "score": 9.5
}}

RULES:
- 2-3 prompts per concept — focus on FLUID/TRANSFORMATION actions, not cutting/pressing
- Every prompt must include camera specs (macro lens, f-stop), lighting, and sound description
- Repeat the same material description, lighting, and camera across all prompts for continuity
- Materials should be visually striking — vibrant colors, interesting textures, unusual combinations
- Satisfaction should come from WATCHING things flow/transform, not from precise physical actions
- Vary the concepts: liquids, color mixing, nature, melting, crystallization, spreading patterns
{past_text}

Return ONLY valid JSON array, no markdown:
[
  {{
    "title": "Under 50 chars, descriptive",
    "sora_prompts": ["Clip 1...", "Clip 2..."],
    "caption": "Short sensory caption",
    "description": "YouTube description with #oddlysatisfying #asmr #Shorts",
    "tags": ["oddly satisfying", "ASMR", "tag3", "tag4", "Shorts"],
    "score": 8.5
  }}
]"""
    return system, user


def refine_sora_prompt(concept: dict, clip_index: int, total_clips: int) -> str:
    """Add Sora-specific style guidance for satisfying content."""
    raw_prompt = concept["sora_prompts"][clip_index]

    style_prefix = (
        "Vertical 9:16 aspect ratio, photorealistic, cinematic macro photography, "
        "shallow depth of field, no text, no watermarks, no UI elements. "
        "Generate rich, detailed ASMR audio synchronized with the visual action. "
    )

    continuity = ""
    if total_clips > 1 and clip_index > 0:
        first_prompt = concept["sora_prompts"][0]
        continuity = f" CRITICAL CONTINUITY: Match the exact same material, lighting, camera angle, and color palette as this scene: \"{first_prompt[:200]}\". "

    if total_clips > 1:
        if clip_index == 0:
            style_suffix = " Opening shot — immediately show the satisfying action in progress. The flow/pour/transformation must be visible from frame 1. No setup, no establishing shots."
        elif clip_index == total_clips - 1:
            style_suffix = continuity + " Final shot — the most satisfying moment. The payoff. Same material, lighting, and camera as the opening."
        else:
            style_suffix = continuity + " Middle shot — the transformation continues. Maintain identical lighting and camera setup."
    else:
        style_suffix = ""

    return style_prefix + raw_prompt + style_suffix
