"""Prompts for Yeah Thats Clean — AI-generated satisfying cleaning Shorts via Sora 2."""

from packages.prompts.idea_detail import build_ideas_prompt_wrapper


# System prompt shared between ideas and full concepts
_SYSTEM = """You generate concepts for AI-generated satisfying cleaning YouTube Shorts.

The channel is "Yeah Thats Clean" — every video shows something FILTHY getting transformed to FLAWLESS. The satisfaction comes from the dramatic before/after transformation.

IMPORTANT — AI VIDEO LIMITATIONS:
These videos are generated by an AI model (Sora 2). The AI is GOOD at:
- Water and fluid dynamics (pressure washing spray, foam spreading, liquid flowing)
- Color transformations (grime dissolving to reveal clean surface underneath)
- Before/after reveals (dirty surface gradually becoming pristine)
- Large-scale environmental scenes (driveways, walls, pools, patios)
- Slow flowing motion (foam spreading, water cascading, chemicals reacting)
- Time-lapse style transformations (rust dissolving, paint restoring)

The AI is BAD at:
- Precise hand/tool close-ups (scrubbing brushes, sponge details)
- Mechanical scrubbing actions (back-and-forth motions look unnatural)
- Small intricate hand movements (wiping with cloth, detailed polishing)
- Realistic human body parts holding cleaning tools
- Text on product labels or brand names

DESIGN CONCEPTS AROUND WHAT AI DOES WELL. Focus on:
- Power washing / pressure washing — water spray blasting away grime (Sora excels at water dynamics)
- Soaking and dissolving — chemicals eating through rust, grease, mold (color transformation)
- Foaming cleaners spreading and lifting dirt (fluid dynamics)
- Paint restoration and color reveal — oxidized surfaces coming back to life
- Rust removal with chemical reactions — bubbling, fizzing, dissolving
- Pool/water cleaning — murky green water turning crystal clear (large-scale color shift)
- Time-lapse style cleaning transformations (nature reclaiming → restored)

AVOID concepts that require:
- Close-up hand scrubbing with brushes or sponges
- Someone wiping with a cloth in precise motions
- Detailed tool manipulation (squeegees, mops, rags)
- Reading product labels or brand names
- Interior household cleaning (too many small objects)

Each clip should show DRAMATIC transformation — the dirtier the start, the more satisfying the clean."""


def build_yeah_thats_clean_ideas_prompt(
    past_titles: list[str] | None = None,
    count: int = 5,
) -> tuple[str, str]:
    """Phase 1: Generate lightweight concept pitches (no Sora prompts)."""
    return build_ideas_prompt_wrapper(_SYSTEM, past_titles, count)


def build_yeah_thats_clean_concepts_prompt(
    past_titles: list[str] | None = None,
    count: int = 5,
) -> tuple[str, str]:
    """Return (system, user) prompts for generating satisfying cleaning concepts."""
    past_text = ""
    if past_titles:
        recent = past_titles[-30:]
        past_text = f"\nAVOID THESE CONCEPTS (already made):\n" + "\n".join(f"- {t}" for t in recent)

    system = _SYSTEM + "\n\nEach concept is a 2-3 clip dirty-to-clean transformation."

    user = f"""Generate {count} satisfying cleaning concepts. Focus on DRAMATIC dirty-to-clean transformations using water, chemicals, foam, and restoration — NOT hand scrubbing or tool manipulation.

EXAMPLE:
{{
  "title": "Pressure Washing a Black Driveway",
  "sora_prompts": [
    "Aerial establishing shot of a concrete driveway completely blackened with years of grime, moss, and oil stains, the surface barely recognizable as concrete, overcast daylight providing even flat lighting, wide angle 24mm lens, the driveway looks abandoned and neglected, ambient outdoor sounds with distant birds",
    "Medium shot of a high-pressure washer stream hitting the black driveway surface, the water jet carving a perfect clean stripe through the grime revealing bright white concrete underneath, water spraying outward carrying black debris, the contrast between clean and dirty is extreme, same overcast daylight, 35mm lens at f/4, satisfying whooshing water pressure sounds with splashing",
    "Wide overhead drone shot showing the driveway now three-quarters cleaned, the dramatic split between pristine white concrete and remaining black grime creating a geometric pattern, water still flowing across the surface catching light, same overcast daylight, 24mm lens, ambient water drainage sounds with a sense of completion"
  ],
  "caption": "Years of grime, gone in minutes",
  "description": "This driveway hadn't been cleaned in YEARS. Watch the transformation. #satisfying #cleaning #pressurewashing #Shorts #oddlysatisfying",
  "tags": ["satisfying", "cleaning", "pressure washing", "oddly satisfying", "Shorts"],
  "score": 9.5
}}

RULES:
- 2-3 prompts per concept — clip 1: dirty reveal, clip 2: cleaning action, clip 3: clean reveal
- Every prompt must include camera specs (lens mm, f-stop), lighting description, and sound description
- Repeat the same location, lighting, and camera style across all prompts for continuity
- The DIRTIER the starting state, the more satisfying the transformation
- Satisfaction comes from WATCHING the transformation happen, not from precise tool work
- Vary the concepts: driveways, walls, pools, cars, fences, roofs, metal, stone, brick, tile
{past_text}

Return ONLY valid JSON array, no markdown:
[
  {{
    "title": "Under 50 chars, descriptive",
    "sora_prompts": ["Clip 1 dirty reveal...", "Clip 2 cleaning action...", "Clip 3 clean reveal..."],
    "caption": "Short punchy caption",
    "description": "YouTube description with #satisfying #cleaning #Shorts",
    "tags": ["satisfying", "cleaning", "tag3", "tag4", "Shorts"],
    "score": 8.5
  }}
]"""
    return system, user


def refine_sora_prompt(concept: dict, clip_index: int, total_clips: int) -> str:
    """Add Sora-specific style guidance for cleaning content."""
    raw_prompt = concept["sora_prompts"][clip_index]

    style_prefix = (
        "Vertical 9:16 aspect ratio, photorealistic, cinematic photography, "
        "high dynamic range, no text, no watermarks, no UI elements. "
        "Generate rich, detailed audio synchronized with the visual action — "
        "water splashing, fizzing, scrubbing, dripping, pressure hissing. "
    )

    continuity = ""
    if total_clips > 1 and clip_index > 0:
        first_prompt = concept["sora_prompts"][0]
        continuity = f" CRITICAL CONTINUITY: Match the exact same location, surface material, lighting, camera angle, and color palette as this scene: \"{first_prompt[:200]}\". "

    if total_clips > 1:
        if clip_index == 0:
            style_suffix = " Opening shot — show the FILTHY surface immediately. The viewer must see how dirty it is from frame 1. No setup, no establishing shots — jump straight to the grime."
        elif clip_index == total_clips - 1:
            style_suffix = continuity + " Final shot — the BIG REVEAL. Show the surface now completely clean and pristine. Same location, same lighting — the transformation is unmistakable."
        else:
            style_suffix = continuity + " Middle shot — the cleaning action in progress. Water, foam, or chemicals actively removing grime. The transformation is happening before our eyes."
    else:
        style_suffix = ""

    return style_prefix + raw_prompt + style_suffix
